package fetcher

import (
	"context"
	"encoding/xml"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"backend/internal/domain"
)

const jinaReaderURL = "https://r.jina.ai/"

// maxArticlesPerGeneration caps how many articles are fetched across an
// entire generation (all requested tags combined), split evenly across the
// distinct feeds those tags resolve to (see FetchArticles). jina.ai Reader
// allows unauthenticated requests at a lower rate limit (see
// https://jina.ai/reader/), and each article also costs one LLM scoring call
// downstream, so this is a deliberate tradeoff between program length and
// generation time/rate-limit risk (backend/CLAUDE.md's known limitation
// notes) rather than a value to maximize: prefer a shorter program that
// finishes reliably over maximizing length and tripping the rate limit
// (verified in production alongside articleFetchPacing below).
const maxArticlesPerGeneration = 16

// articleFetchPacing spaces out consecutive jina.ai Reader requests within
// one generation. Firing maxArticlesPerGeneration requests back to back
// tripped jina.ai's unauthenticated per-IP rate limit after only a handful
// succeeded (verified in production); pacing trades a bit of wall-clock time
// for most of the budget actually succeeding.
const articleFetchPacing = 2 * time.Second

// tagFeeds maps preset tags to a specific public RSS feed, for the handful of
// tags with an obvious one-to-one match. It predates the current 100-tag
// preset list (config/tags.json, generated by cmd/gentags from real feed
// content) and only covers a small, unrelated earlier tag set — most tags
// fall through to defaultFeeds below.
var tagFeeds = map[string]string{
	"ai":   "https://news.yahoo.co.jp/rss/topics/it.xml",
	"京都":   "https://news.yahoo.co.jp/rss/topics/local.xml",
	"ゲーム":  "https://news.yahoo.co.jp/rss/topics/it.xml",
	"音楽":   "https://news.yahoo.co.jp/rss/topics/entertainment.xml",
	"スポーツ": "https://news.yahoo.co.jp/rss/topics/sports.xml",
	"ビジネス": "https://news.yahoo.co.jp/rss/topics/business.xml",
	"映画":   "https://news.yahoo.co.jp/rss/topics/entertainment.xml",
	"旅行":   "https://news.yahoo.co.jp/rss/topics/local.xml",
}

// defaultFeeds is used for any tag with no specific mapping in tagFeeds —
// in practice almost every tag in the current 100-tag preset list, which is
// IT/tech-skewed (config/tags.json). A single shared fallback feed meant
// that picking 2-3 such tags in one generation pulled from the exact same
// feed each time, collapsing to near-duplicate articles after deduplication
// and producing programs far shorter than requested (verified in
// production: 3 unmapped tags → 1-2 surviving chapters). Pooling several
// feeds across categories means an unmapped tag still contributes a mix of
// distinct real articles instead of one repeated source.
var defaultFeeds = []string{
	"https://news.yahoo.co.jp/rss/topics/it.xml",
	"https://news.yahoo.co.jp/rss/topics/business.xml",
	"https://news.yahoo.co.jp/rss/topics/domestic.xml",
}

// JinaFetcher retrieves article text through the jina.ai Reader API.
type JinaFetcher struct {
	client *http.Client
}

// NewJinaFetcher creates a Jina Reader-backed Fetcher. A nil client uses the
// default HTTP client.
func NewJinaFetcher(client *http.Client) *JinaFetcher {
	if client == nil {
		client = http.DefaultClient
	}
	return &JinaFetcher{client: client}
}

// FetchArticles discovers real article URLs for the requested tags via their
// mapped RSS feed(s) (feedsForTag), then fetches each one through jina.ai
// Reader. Used by the on-the-spot generation path
// (backend/docs/pipeline/01-fetch.md). JINA_AI_API_KEY is optional; real
// fetches are attempted either way (see fetchArticle). A single article or
// feed failing (bot-blocked, removed, RSS temporarily down, etc.) is skipped
// rather than aborting the whole batch, since that's common enough with real
// websites/feeds that it shouldn't take down generation for everything else
// that did succeed.
//
// Feeds are resolved and deduplicated across ALL tags before fetching
// (uniqueFeedsForTags), not per tag: most tags in the current 100-tag preset
// list share the same fallback pool (defaultFeeds), and fetching that pool
// once per tag re-requested the exact same top RSS items 2-3 times over,
// which then collapsed back down to just a handful of distinct articles
// after deduplication — producing programs far shorter than requested even
// with a generous per-tag budget (verified in production).
//
// Article fetches are paced articleFetchPacing apart rather than fired back
// to back: jina.ai Reader's unauthenticated tier has a per-IP rate limit
// tight enough that requesting maxArticlesPerGeneration articles without any
// spacing tripped it after only a handful succeeded (verified in
// production: 20+ of 24 came back 429 within a few seconds). Pacing keeps
// the same total budget but lets most of it actually succeed instead.
func (f *JinaFetcher) FetchArticles(ctx context.Context, tags []string) ([]domain.Article, error) {
	feeds := uniqueFeedsForTags(tags)
	if len(feeds) == 0 {
		return nil, nil
	}
	perFeedLimit := (maxArticlesPerGeneration + len(feeds) - 1) / len(feeds)

	articles := make([]domain.Article, 0)
	firstFetch := true
	for _, feedURL := range feeds {
		sourceURLs, err := fetchFeedURLs(ctx, f.client, feedURL, perFeedLimit)
		if err != nil {
			log.Printf("fetcher: skipping feed %q: %v", feedURL, err)
			continue
		}

		for _, sourceURL := range sourceURLs {
			if !firstFetch {
				select {
				case <-ctx.Done():
					return articles, ctx.Err()
				case <-time.After(articleFetchPacing):
				}
			}
			firstFetch = false

			article, err := f.fetchArticle(ctx, sourceURL)
			if err != nil {
				log.Printf("fetcher: skipping article %q: %v", sourceURL, err)
				continue
			}
			articles = append(articles, article)
		}
	}
	return articles, nil
}

// FetchArticle retrieves and normalizes the body for one article URL through
// jina.ai Reader, for callers that already have their own URL (cmd/ingest,
// which reads URLs from the RSS feeds listed in config/rss.json rather
// than tagFeeds — see backend/docs/generation/02-ingestion.md). This always
// performs a live Reader request, same as fetchArticle (used internally by
// FetchArticles' tag-based cmd/demo path) — jina.ai Reader supports
// unauthenticated requests at a lower rate limit, so a missing
// JINA_AI_API_KEY only affects throughput, not whether the fetch is real
// (see MockMode). Callers that already have RSS metadata should replace the
// returned title, publication time, and source name with that metadata.
func (f *JinaFetcher) FetchArticle(ctx context.Context, sourceURL string) (domain.Article, error) {
	return f.fetchArticle(ctx, sourceURL)
}

// feedsForTag returns the RSS feed mapped to tag if one exists, or
// defaultFeeds (the whole pool) otherwise.
func feedsForTag(tag string) []string {
	if feedURL, ok := tagFeeds[strings.ToLower(strings.TrimSpace(tag))]; ok {
		return []string{feedURL}
	}
	return defaultFeeds
}

// uniqueFeedsForTags resolves every tag to its feed(s) via feedsForTag and
// returns the deduplicated union, preserving first-seen order. Tags sharing
// a feed (the common case, since most tags fall back to the same
// defaultFeeds pool) must only cause that feed to be fetched once per
// generation — see FetchArticles.
func uniqueFeedsForTags(tags []string) []string {
	seen := make(map[string]struct{})
	feeds := make([]string, 0, len(tags))
	for _, tag := range tags {
		for _, feedURL := range feedsForTag(tag) {
			if _, ok := seen[feedURL]; ok {
				continue
			}
			seen[feedURL] = struct{}{}
			feeds = append(feeds, feedURL)
		}
	}
	return feeds
}

// rssFeed is the minimal RSS 2.0 shape needed to pull article links out of a
// feed (see https://www.rssboard.org/rss-specification).
type rssFeed struct {
	Channel struct {
		Items []struct {
			Link string `xml:"link"`
		} `xml:"item"`
	} `xml:"channel"`
}

// fetchFeedURLs fetches feedURL directly (RSS is plain XML, so this doesn't
// go through jina.ai Reader or Firecrawl) and returns up to limit article
// link URLs. Shared by both fetcher providers.
func fetchFeedURLs(ctx context.Context, client *http.Client, feedURL string, limit int) ([]string, error) {
	if client == nil {
		client = http.DefaultClient
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, feedURL, nil)
	if err != nil {
		return nil, err
	}

	response, err := client.Do(request)
	if err != nil {
		return nil, err
	}
	defer response.Body.Close()

	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("rss feed returned status %d", response.StatusCode)
	}

	var feed rssFeed
	if err := xml.NewDecoder(response.Body).Decode(&feed); err != nil {
		return nil, fmt.Errorf("parse rss feed: %w", err)
	}

	urls := make([]string, 0, limit)
	for _, item := range feed.Channel.Items {
		link := strings.TrimSpace(item.Link)
		if link == "" {
			continue
		}
		urls = append(urls, link)
		if len(urls) >= limit {
			break
		}
	}
	return urls, nil
}

// fetchArticle performs the actual jina.ai Reader HTTP request, always live
// (no mock fallback). Used directly by FetchArticles' tag-based cmd/demo
// path; the exported FetchArticle wraps this with a MockMode check instead,
// for cmd/ingest.
func (f *JinaFetcher) fetchArticle(ctx context.Context, sourceURL string) (domain.Article, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, jinaReaderURL+sourceURL, nil)
	if err != nil {
		return domain.Article{}, err
	}
	request.Header.Set("Accept", "text/markdown")
	if apiKey := strings.TrimSpace(os.Getenv("JINA_AI_API_KEY")); apiKey != "" {
		request.Header.Set("Authorization", "Bearer "+apiKey)
	}

	client := f.client
	if client == nil {
		client = http.DefaultClient
	}
	response, err := client.Do(request)
	if err != nil {
		return domain.Article{}, err
	}
	defer response.Body.Close()

	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		body, _ := io.ReadAll(io.LimitReader(response.Body, 4096))
		return domain.Article{}, fmt.Errorf("jina reader returned status %d: %s", response.StatusCode, strings.TrimSpace(string(body)))
	}
	body, err := io.ReadAll(response.Body)
	if err != nil {
		return domain.Article{}, err
	}

	return articleFromContent(string(body), sourceURL), nil
}

// MockMode reports whether Jina credentials are absent, meaning requests go
// out unauthenticated at jina.ai Reader's lower rate limit rather than being
// mocked (all fetches are live regardless — see FetchArticle/fetchArticle).
// Callers use this only to log a heads-up about the reduced rate limit.
func (f *JinaFetcher) MockMode() bool {
	return strings.TrimSpace(os.Getenv("JINA_AI_API_KEY")) == ""
}

func articleFromContent(content, sourceURL string) domain.Article {
	parsedURL, _ := url.Parse(sourceURL)
	sourceName := parsedURL.Hostname()
	if sourceName == "" {
		sourceName = "unknown"
	}

	return domain.Article{
		Title:       titleFromContent(content, sourceURL),
		Body:        strings.TrimSpace(content),
		PublishedAt: time.Now().UTC(),
		SourceName:  sourceName,
		SourceURL:   sourceURL,
	}
}

func titleFromContent(content, sourceURL string) string {
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "#") {
			return strings.TrimSpace(strings.TrimLeft(line, "#"))
		}
	}
	if parsedURL, err := url.Parse(sourceURL); err == nil && parsedURL.Path != "" {
		path := strings.Trim(parsedURL.Path, "/")
		if path != "" {
			parts := strings.Split(path, "/")
			return parts[len(parts)-1]
		}
	}
	return sourceURL
}

func mockArticles(tags []string, provider string) []domain.Article {
	const mockArticlesPerTag = 2
	articles := make([]domain.Article, 0, len(tags)*mockArticlesPerTag)
	now := time.Now().UTC()
	for _, tag := range tags {
		tag = strings.TrimSpace(tag)
		if tag == "" {
			continue
		}
		for index := 1; index <= mockArticlesPerTag; index++ {
			articles = append(articles, domain.Article{
				Title:       fmt.Sprintf("[MOCK] %s topic %d (%s)", tag, index, provider),
				Body:        fmt.Sprintf("[MOCK] This is sample article %d for the %s tag.", index, tag),
				PublishedAt: now.Add(-time.Duration(index) * time.Hour),
				SourceName:  fmt.Sprintf("%s-mock", provider),
				SourceURL:   fmt.Sprintf("https://example.com/mock/%s/%d", url.PathEscape(tag), index),
			})
		}
	}
	return articles
}

var _ Fetcher = (*JinaFetcher)(nil)
